apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-test.fullname" . }}
  labels:
    {{- include "node-test.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      targetPort: {{ .Values.service.port }}
      port: {{ .Values.service.port }}
  selector:
    {{- include "node-test.selectorLabels" . | nindent 4 }}
